/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Pumkin
 */
public class GamePanel extends javax.swing.JPanel {

    public javax.swing.border.Border pikachuBorder = BorderFactory.createLineBorder(Color.yellow);
    
    /**
     * Creates new form StartPanel
     */
    public GamePanel() {
        initComponents();
        
        pikachuLabels = new ArrayList<>();
        
        pikachu1 = new javax.swing.JLabel();
        pikachuLabels.add(pikachu1);
        
        pikachu2 = new javax.swing.JLabel();
        pikachuLabels.add(pikachu2);
        
        pikachu3 = new javax.swing.JLabel();
        pikachuLabels.add(pikachu3);
        
        pikachu4 = new javax.swing.JLabel();
        pikachuLabels.add(pikachu4);
        
        pikachu5 = new javax.swing.JLabel();
        pikachuLabels.add(pikachu5);
    }

    public void setPikachu(List<String> pikachuImgs, int numImgs) throws IOException{
        
        Random rand = new Random();
        
        for(int i = 0; i < numImgs; i++){
            
            int randomX = rand.nextInt(800);
            int randomY = rand.nextInt(500);

            BufferedImage img = ImageIO.read(new File(pikachuImgs.get(i)));
            ImageIcon imageIcon = new javax.swing.ImageIcon(img);
            this.pikachuLabels.get(i).setIcon(imageIcon);
            this.pikachuLabels.get(i).setLocation(randomX, randomY);
            this.pikachuLabels.get(i).setName("pikachu" + i);
            this.pikachuLabels.get(i).setVisible(true);
            
            this.add(this.pikachuLabels.get(i));
        }
    }
    
    public void setPokemon(List<String> pokemonImgs, int numImgs) throws IOException{
        
        Random rand = new Random();
        
        for(int i = 0; i < numImgs; i++){
            
            int randomX = rand.nextInt(800);
            int randomY = rand.nextInt(500);
            int randomI = rand.nextInt(pokemonImgs.size());
            String randomMon = pokemonImgs.get(randomI);
            System.out.println(randomMon);
            
            JLabel label = new javax.swing.JLabel();
            BufferedImage img = ImageIO.read(new File(randomMon));
            label.setIcon(new javax.swing.ImageIcon(img));
            label.setLocation(randomX, randomY);
            label.setVisible(true);
            
            this.add(label);
            
            label.repaint();
        }
    }
    
    public void setNumPikachu(int numFound){
        this.numFoundLabel.setText(String.valueOf(numFound));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numFoundLabel = new javax.swing.JLabel();
        finishBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        numPikachuLabel = new javax.swing.JLabel();
        bgPanel = new javax.swing.JPanel();
        bgLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(null);

        jLabel1.setText("Pikachu found");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 16));
        add(jLabel1);
        jLabel1.setBounds(912, 6, 100, 16);

        numFoundLabel.setText("0");
        numFoundLabel.setPreferredSize(new java.awt.Dimension(50, 16));
        add(numFoundLabel);
        numFoundLabel.setBounds(924, 28, 50, 16);

        finishBtn.setText("Finish");
        add(finishBtn);
        finishBtn.setBounds(918, 72, 63, 32);

        jLabel2.setText("out of: ");
        add(jLabel2);
        jLabel2.setBounds(918, 50, 38, 16);

        numPikachuLabel.setText("0");
        add(numPikachuLabel);
        numPikachuLabel.setBounds(962, 50, 39, 16);

        bgPanel.setLayout(new javax.swing.OverlayLayout(bgPanel));
        add(bgPanel);
        bgPanel.setBounds(0, 0, 0, 0);

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bg/bg.png"))); // NOI18N
        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bg/bg.png")));
        add(bgLabel);
        bgLabel.setBounds(0, 0, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    public List<JLabel> pikachuLabels;

    public javax.swing.JLabel pikachu1;
    public javax.swing.JLabel pikachu2;
    public javax.swing.JLabel pikachu3;
    public javax.swing.JLabel pikachu4;
    public javax.swing.JLabel pikachu5;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JPanel bgPanel;
    public javax.swing.JButton finishBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel numFoundLabel;
    public javax.swing.JLabel numPikachuLabel;
    // End of variables declaration//GEN-END:variables
}
